app:
  build: ./backend
  command: python -u main.py
  ports:
    - "$PORT:$PORT"
  volumes:
    - ./backend:/backend
  environment:
    - PORT=$PORT
  links:
    - db
db:
  image: mongo:latest
  hostname: test_mongodb
  environment:
    - MONGO_INITDB_DATABASE=shopify_db
    # - MONGO_INITDB_ROOT_USERNAME=root
    # - MONGO_INITDB_ROOT_PASSWORD=pass
  ports:
    - 27017:27017